# Generated by Django 4.2.1 on 2023-06-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_id_school__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='_id',
            new_name='id',
        ),
    ]
